spring:
  application.name: EtherStore


stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD, EUR, GBP


payment-gateway: PayPal



mail:
  host: https://spring_boot.gmail.com
  port: 5761
